### ISSUE TITLE
1 thread?

### ISSUE THREAD

**Issue by AsoSunag** [alexhultman/Node.js-needs-to-die-in-a-fire-and-Golang-is-the-perfect-arsonist#12]
Can You explain what you mean by 1 thread for:

- Golang: from what I remember you can only change the GOMAXPROCS which "limits the number of operating system threads that can execute user-level Go code simultaneously" (quote from the Golang runtime package), not the maximum number of threads allocated to system or network call. Is that what you did?

- Node.js: Did you launch node with a single threaded V8 or are you talking about the single threaded event loop?

**Comment by paralin** [comment]
GOMAXPROCS=1 most definitely would be a single thread for the entire program. The Go runtime schedules goroutines onto threads, one per cpu core, or in the case of maxprocs=1 a single thread. The go runtime is written in Go and uses goroutines so it makes sense that only one is in use at a time, using event-based io.

**Comment by alexhultman** [comment]
GOMAXPROCS=1 yes. Without it I got 250k requests/second.
