### ISSUE TITLE
Special Olympics comment was unnecessary

### ISSUE THREAD

**Issue by mackenza** [alexhultman/Node.js-needs-to-die-in-a-fire-and-Golang-is-the-perfect-arsonist#13]
Why did you feel the need to belittle intellectually disabled people (and they are people, with feelings and emotions, just so you know) in a diatribe on NodeJS? Juvenile, ignorant, cheap humor.

**Comment by alexhultman** [comment]
Oh wow. You kind of shot yourself in the foot here. Why would you say that these people are intellectually disabled? What are you? A racist or something? Shame on you.
