### ISSUE TITLE
Why are you only considering performance? 

### ISSUE THREAD

**Issue by mauvm** [alexhultman/Node.js-needs-to-die-in-a-fire-and-Golang-is-the-perfect-arsonist#3]
And I'm curious how a library like Martini performs, can you please add a benchmark for that as well? Maybe fasthttp-router too?

**Comment by alexhultman** [comment]
No. Read #1. This is not a benchmarking post, it just shows how terrible Node.js performs (using a few counter examples which happen to be fasthttp and net/http).
