### ISSUE TITLE
Ruby on rails the fastest?

### ISSUE THREAD

**Issue by jbcpollak** [alexhultman/Node.js-needs-to-die-in-a-fire-and-Golang-is-the-perfect-arsonist#5]
Is that right? RoR served 200k requests per second?

**Comment by jbcpollak** [comment]
Oops, just noticed there was no 'k' after the 200, nevermind

**Comment by aichholzer** [comment]
Literally, LOL.

**Comment by alexhultman** [comment]
Hehe, it's funny because both are wrong :wink:
