### ISSUE TITLE
Post the benchmark code

### ISSUE THREAD

**Issue by jbcpollak** [alexhultman/Node.js-needs-to-die-in-a-fire-and-Golang-is-the-perfect-arsonist#6]
Please share the code you used to generate the numbers!

**Comment by alexhultman** [comment]
No. This is not meant to be a scientific post with boring details, those numbers are just a very rough estimate of simple http as one basic example. If you want some serious benchmarking you can look into my other projects where these kinds of boring details are openly available.

**Comment by Nepoxx** [comment]
tl;dr "Trust my benchmarks that confirm my bias"

For actual valid benchmarks, look at https://www.techempower.com/benchmarks/

They are open-source and test a lot of things you that you actually use on servers. For instance, Node.js outperform Go in JSON serialization: https://www.techempower.com/benchmarks/#section=data-r14&hw=ph&test=json
