### ISSUE TITLE
Not Go, Crystal

### ISSUE THREAD

**Issue by aichholzer** [alexhultman/Node.js-needs-to-die-in-a-fire-and-Golang-is-the-perfect-arsonist#8]
https://crystal-lang.org
I'm sure you will like this one.

**Comment by alexhultman** [comment]
https://fortran.io/

**Comment by aichholzer** [comment]
> Fortran is like PHP.

Humm... No, thank you.

**Comment by alexhultman** [comment]
Hehehe but Fortran is almost older than the US as a country. That makes it hip and modern.

**Comment by aichholzer** [comment]
> Hip and modern

You just answered yourself as to why Node has become so popular.
😎
